CREATE TABLE `content_plan_items` (
  `id` CHAR(36) NOT NULL,
  `content_id` VARCHAR(191) NOT NULL,
  `date` DATE NOT NULL,
  `day` VARCHAR(20) NOT NULL,
  `test_publish_window` VARCHAR(50) NOT NULL,
  `pillar` VARCHAR(100) NOT NULL,
  `goal` VARCHAR(100) NOT NULL,
  `format` VARCHAR(100) NOT NULL,
  `creative_style` VARCHAR(100) NOT NULL,
  `audience` TEXT NOT NULL,
  `topic_tag` VARCHAR(120) NOT NULL,
  `working_title` VARCHAR(255) NOT NULL,
  `hook` TEXT NOT NULL,
  `core_angle` TEXT NOT NULL,
  `slide_1` TEXT NOT NULL,
  `slide_2` TEXT NOT NULL,
  `slide_3` TEXT NOT NULL,
  `slide_4_5` TEXT NOT NULL,
  `visual_direction` TEXT NOT NULL,
  `cta` TEXT NOT NULL,
  `caption_brief` TEXT NOT NULL,
  `primary_metric` VARCHAR(100) NOT NULL,
  `secondary_metric` VARCHAR(191) NOT NULL,
  `engagement_mechanic` TEXT NOT NULL,
  `story_companion` TEXT NOT NULL,
  `experiment_tag` VARCHAR(255) NOT NULL,
  `product_focus` VARCHAR(255) NOT NULL,
  `claim_guardrail` TEXT NOT NULL,
  `assets_needed` TEXT NOT NULL,
  `status` ENUM('planned','approved_for_creation','creating','ready_for_review','approved','scheduled','published','measuring') NOT NULL DEFAULT 'planned',
  `approval_status` VARCHAR(50) NOT NULL,
  `publish_status` VARCHAR(50) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `content_plan_items_content_id_key` (`content_id`),
  INDEX `content_plan_items_date_status_idx` (`date`,`status`),
  INDEX `content_plan_items_pillar_idx` (`pillar`),
  INDEX `content_plan_items_topic_tag_idx` (`topic_tag`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
