import type { Metadata } from "next";
import LegalDocument, { PRIVACY_EMAIL } from "../legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy | Staff Sosmed ASM",
  description: "Privacy Policy for Staff Sosmed ASM, an internal social media management and analytics application operated by PT Auri Steel Metalindo.",
};

const list = (items: string[]) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" subtitle="Staff Sosmed ASM · Operated by PT Auri Steel Metalindo" updated="Last updated: 26 August 2026" alternate={{ href: "/data-deletion", label: "Data Deletion Instructions" }} sections={[
    { title: "About This Application", content: <><p>Staff Sosmed ASM is an internal social media management and analytics application operated by PT Auri Steel Metalindo.</p><p>The application is used to assist authorized company personnel in planning content, managing approved social media publications, monitoring content performance, and analyzing engagement from Facebook Pages and Instagram Business accounts owned or managed by PT Auri Steel Metalindo.</p><p>The application is not offered as a public consumer service and is not used to provide social media management services to unrelated third parties.</p></> },
    { title: "Information We Access", content: <><p>When authorized through Meta Platforms, Staff Sosmed ASM may access information made available through the Meta Graph API for Facebook Pages and Instagram Business accounts connected to PT Auri Steel Metalindo.</p><p>Depending on the permissions granted, this may include:</p>{list(["Facebook Page information;","Instagram Business account information;","account name and username;","media and post identifiers;","captions;","media type;","media URLs and thumbnail URLs;","publication timestamps;","post permalinks;","carousel media information;","engagement and performance metrics made available by Meta, including reach, impressions or views, likes, comments, saves, shares, and related insights."])}<p>Staff Sosmed ASM only accesses information required for the functions authorized by PT Auri Steel Metalindo.</p></> },
    { title: "How We Use Information", content: <><p>Information obtained through Meta Platforms is used solely for legitimate internal business purposes of PT Auri Steel Metalindo, including:</p>{list(["preparing and managing social media content plans;","reviewing content before publication;","publishing content that has been approved by authorized personnel;","displaying social media performance in an internal analytics dashboard;","monitoring engagement and content performance;","comparing the performance of different posts and content formats;","evaluating content topics and creative approaches;","evaluating publication timing;","improving future social media content and communication strategies."])}<p>Data obtained through Meta is not used for unrelated purposes.</p></> },
    { title: "Publishing Controls", content: <><p>Staff Sosmed ASM may provide functionality to publish approved content to authorized Instagram Business or Facebook Page accounts.</p><p>Publication actions are performed only within the scope authorized by PT Auri Steel Metalindo and the permissions granted through Meta Platforms.</p><p>Internal approval controls may be used before content is published.</p></> },
    { title: "Data Storage", content: <><p>Information required for application functionality may be stored in infrastructure controlled or administered by PT Auri Steel Metalindo.</p><p>Stored information may include content records, publication metadata, social media identifiers, analytics snapshots, and application operational records.</p><p>Access credentials and authentication tokens are not exposed through public application interfaces.</p></> },
    { title: "Data Security", content: <><p>PT Auri Steel Metalindo applies reasonable technical and organizational safeguards designed to protect information processed by Staff Sosmed ASM.</p><p>These measures include access controls, restricted application credentials, environment-based secret management, and limitation of application access to authorized personnel and systems.</p></> },
    { title: "Data Sharing", content: <><p>PT Auri Steel Metalindo does not sell personal information or Meta Platform data obtained through Staff Sosmed ASM.</p><p>Meta Platform data is not sold, rented, or provided to third parties for their independent advertising or marketing purposes.</p><p>Information may only be processed by systems or service providers necessary to operate the application and company infrastructure, subject to appropriate access controls.</p></> },
    { title: "Data Retention", content: <><p>Information is retained only for as long as reasonably necessary for the operational, analytical, security, or compliance purposes for which it was collected.</p><p>Data that is no longer required may be deleted, anonymized, or aggregated in accordance with PT Auri Steel Metalindo&apos;s internal data management practices and applicable requirements.</p></> },
    { title: "User and Platform Data Deletion", content: <><p>Authorized users may request deletion of information associated with Staff Sosmed ASM.</p><p>Detailed deletion instructions are available at:</p><p><a href="https://sosmedasm.rsby.cloud/data-deletion">https://sosmedasm.rsby.cloud/data-deletion</a></p><p>Valid deletion requests will be reviewed and processed in accordance with applicable requirements and legitimate retention obligations.</p></> },
    { title: "Meta Platforms", content: <><p>Staff Sosmed ASM uses APIs and services provided by Meta Platforms, Inc. to access authorized Facebook Page and Instagram Business functionality.</p><p>Access to Meta Platform data is subject to the permissions granted to the application and applicable Meta Platform terms and policies.</p></> },
    { title: "Changes to This Privacy Policy", content: <><p>PT Auri Steel Metalindo may update this Privacy Policy when application functionality, data usage, platform requirements, or applicable practices change.</p><p>The latest version will remain available at this URL.</p></> },
    { title: "Contact", content: <><p><strong>PT Auri Steel Metalindo</strong></p><p>Questions regarding privacy, data access, or deletion requests may be submitted through the official contact channels of PT Auri Steel Metalindo.</p><p>Privacy contact: <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a></p></> },
  ]} />;
}
